### ISSUE TITLE
Enable RTTI

### ISSUE THREAD

**Issue by zenna** [Keno/Cxx.jl#104]
i have been using the C++ IBEX constraint programming library with Cxx.

On my first attempt, when including `ibex.h`, I got a ton of errors about the fact that RTTI was not enabled.  To fix, in [src/bootstrap.cpp](https://github.com/Keno/Cxx.jl/blob/166ed8e31e76528d34e9cb0b206df351dff9750c/src/bootstrap.cpp#L724), I changed

```Cxx->CI->getLangOpts().RTTI = 0;```

to

```Cxx->CI->getLangOpts().RTTI = 1;```

then rebuilt Cxx, and everything works fine.

So is there a reason it is disabled by default? Is my fix going to cause problems elsewhere? Is there a better way?

**Comment by Keno** [comment]
Nope, this is fine. RTTI adds a bit of overhead and I haven't needed it so far, which is why it was disabled. Feel free to make a PR to enable it though.

**Comment by jpata** [comment]
In case we enable this we can do the following:
https://gist.github.com/jpata/398fa8ab8eb741b649baca40cde9cd9f

**Comment by Keno** [comment]
The problem is that depending on what option you choose, you will not be able to use a library that was built with the opposite option. I think what we may have to do is enable RTTI but be robust to situations in which it doesn't exist, maybe by hacking around it in the linker. Not sure, will have to ponder.

**Comment by oschulz** [comment]
I'd also like to have RTTI available, if possible.
