### ISSUE TITLE
Transfer to JuliaInterop?

### ISSUE THREAD

**Issue by ViralBShah** [Keno/Cxx.jl#291]
Perhaps Cxx.jl could live in JuliaInterop long term?

**Comment by Keno** [comment]
I've mentioned before that I don't think JuliaInterop is necessarily the right kind of organization, because e.g. interaction with C++ has very little to do with interacting with Python or R or MATLAB, so grouping those packages makes little sense. I could see there being a JuliaCxx organization like we have JuliaPy, but I think that's a little ways off.

**Comment by ViralBShah** [comment]
Sorry for the noise.

**Comment by tkelman** [comment]
You should at least give several other people commit access (to this and any other package under your personal account) in case something urgently needs doing while you're unavailable.

**Comment by StefanKarpinski** [comment]
Why not just create JuliaCxx now and transfer Cxx and CxxWrap to it? I don't understand the point of delaying.

**Comment by tkelman** [comment]
Even if there's no technical overlap, organizationally it makes things a little easier to find to have them under a topical organization.

**Comment by StefanKarpinski** [comment]
There are many other benefits that we've seen over and over again – better communication, cross-pollination of ideas, discovering that there actually are potential areas of technical overlap.
