### ISSUE TITLE
Examples using Cxx to wrap C++ libraries

### ISSUE THREAD

**Issue by zenna** [Keno/Cxx.jl#97]
I imagine one of the most popular use cases for Cxx is to wrap existing C++ libraries.  Although the examples demonstrate how to use Cxx, the leap from the simple examples to including and linking to other libraries is not obvious (at least not for me).

Searching through Github I found [OpenCV.jl](https://github.com/maxruby/OpenCV.jl/tree/master/src), which is actually an amazing resource of how to do just this.  So I suppose all I am saying is I would suggest either adding a section to thincludesincludese Readme which lists current projects which are using Cxx (the few that there are); or adding a simple example which demonstrates the use of shared libraries, or both.

**Comment by ihnorton** [comment]
The tests directory has several examples (e.g. LLVM; Qt with event loop integration).

**Comment by Keno** [comment]
I put up https://github.com/Keno/Pythia.jl. It's fairly minimal since I mostly use the C++ REPL to interact with it, but it has some fun iterator wrappers, so maybe that's helpful.

**Comment by Keno** [comment]
There's now also https://github.com/JuliaComputing/ArrayFire.jl. In general my strategy for writing wrapper is to actually prefer to expose the C++ to users of the wrapper and only extra convenience functionality as well as dealing with binary dependencies in the wrapper. ArrayFire is a bit of a special case, since you really want to integrate it with julia's native array libraries, so it has more wrapping than a lot of other wrapper I've written.
